import { faGoogle } from '@fortawesome/free-brands-svg-icons'
import {
  faEnvelope,
  faRightToBracket,
  faUserPlus,
  faCircleArrowRight,
  faCircleArrowLeft,
  faCirclePlus,
  faCalendarMinus,
  faCheck,
  faEllipsisVertical,
  faArrowRightFromBracket,
  faSliders,
  faMinus,
  faPlus,
  faUtensils,
  faBagShopping,
  faHouseUser,
  faBus,
  faCar,
  faPerson,
  faDesktop, faBars
} from '@fortawesome/free-solid-svg-icons'

export default [
  faEnvelope,
  faCirclePlus,
  faUtensils,
  faBagShopping,
  faHouseUser,
  faBus,
  faCar,faBars,
  faPerson,
  faDesktop,
  faRightToBracket,
  faCalendarMinus,
  faUserPlus,
  faCircleArrowRight,
  faCircleArrowLeft,
  faGoogle,
  faSliders,
  faCheck,
  faEllipsisVertical,
  faMinus,
  faPlus,
  faArrowRightFromBracket
]
